services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "root"
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - .:/app
      - sqlite_data:/var/data:z
    depends_on:
      redis:
        condition: service_started
      clickhouse:
        condition: service_healthy
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data
    env_file:
      - .env
    restart: unless-stopped
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_SKIP_USER_SETUP: 1
      CLICKHOUSE_DB: "logs"
    ports:
      - "9000:9000"
      - "8123:8123"
    healthcheck:
        test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
        interval: 3s
        timeout: 3s
        retries: 10
        start_period: 5s

volumes:
  sqlite_data:
    driver: local
  redis-data:
    driver: local
